### ISSUE TITLE
Random connection drops during mail protocol logon when using HTTP CONNECT proxy

### ISSUE THREAD

**Issue by nicowiggersiv** [eclipse-ee4j/angus-mail#45]
**Describe the bug**
We have noticed random connection issues when connecting to mail services via proxy connection (HTTP CONNECT). The protocol connect sometimes hangs until the server closes the connection after a timeout, e.g., a dovecot server sends "BYE Disconnected for inactivity.".

Here is a sample stacktrace for this case:

```
com.sun.mail.iap.ConnectionException: * BYE Disconnected for inactivity.
	at jakarta.mail@2.0.1/com.sun.mail.imap.protocol.IMAPProtocol.processGreeting(IMAPProtocol.java:297)
	at jakarta.mail@2.0.1/com.sun.mail.iap.Protocol.<init>(Protocol.java:116)
	at jakarta.mail@2.0.1/com.sun.mail.imap.protocol.IMAPProtocol.<init>(IMAPProtocol.java:107)
	at jakarta.mail@2.0.1/com.sun.mail.imap.IMAPStore.newIMAPProtocol(IMAPStore.java:739)
	at jakarta.mail@2.0.1/com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:674)
	at jakarta.mail@2.0.1/com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:714)
	at jakarta.mail@2.0.1/jakarta.mail.Service.connect(Service.java:342)
	at de.siv.test/de.siv.Test.test(Test.java:161)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**To Reproduce**
Use proxy (HTTP CONNECT) to connect to mail service. Use non-encrypted connections. Issue is only seen in cases where there is not much time between the client receiving the HTTP response and the mail protocol server greeting.

**Expected behavior**
The client proceeds to communicate with the server.

**Mail server:**
 - Protocol being used: at least imap and smtp are affected
 - Vendor/product: dovecot, postfix
 - Mail service URL: enterprise internal server
 
**Preliminary cause analysis**

I have done some paket traces and I have noticed that this issue seems to occur only when the server response for HTTP CONNECT and the server mail protocol greeting are transmitted close togehter. After checking the jakart.mail source code, I am pretty sure I have found the cause of this issue. In SocketFetcher.proxyConnect a BufferedReader is temporarily used to read the HTTP response, after we have sent the HTTP CONNECT message. In this case, the BufferedReader might also read the first mail protocol data from the socket, the greeting message. After proxyConnect() the BufferedReader is discarded  and with it the first server message, at least in this case where the socket had already received this message. 

![image](https://user-images.githubusercontent.com/25098345/205890232-47ae8c45-b46b-4bbc-8f33-9e4c759a269f.png)

Here is the code of SocketFetcher.java:

```java
    private static void proxyConnect(Socket socket,
				String proxyHost, int proxyPort,
				String proxyUser, String proxyPassword,
				String host, int port, int cto)
				throws IOException {
        ...
	BufferedReader r = new BufferedReader(new InputStreamReader(
			    socket.getInputStream(), StandardCharsets.UTF_8));
	String line;
	boolean first = true;
	while ((line = r.readLine()) != null) {
	    if (line.length() == 0)
		break;
	    logger.finest(line);
	    if (first) {
		StringTokenizer st = new StringTokenizer(line);
		String http = st.nextToken();
		String code = st.nextToken();
		if (!code.equals("200")) {
		    try {
			socket.close();
		    } catch (IOException ioex) {
			// ignored
		    }
		    ConnectException ex = new ConnectException(
			"connection through proxy " +
			proxyHost + ":" + proxyPort + " to " +
			host + ":" + port + " failed: " + line);
		    logger.log(Level.FINE, "connect failed", ex);
		    throw ex;
		}
		first = false;
	    }
	}
    }
```

It is worth noting, that this issue only occurs with non-TLS connections. When using TLS connections, after the HTTP CONNECT, the client first needs to initiate the TLS connection and does not a receive a server greeting right after the HTTP CONNECT.

**Comment by jbescos** [comment]
Hi @nicowiggersiv 

I am trying it with this HTTP proxy that I developed recently: [HttpProxy](https://github.com/jbescos/HttpProxy)

And I am running the next [example](https://github.com/jbescos/jakartaEE10MailDemo), configuring the proxy in this way:
```
        MAIL_PROPERTIES.setProperty("mail.imap.host", "0.0.0.0");
        MAIL_PROPERTIES.setProperty("mail.imap.port", "18004");
        MAIL_PROPERTIES.setProperty("mail.imap.proxy.host", "localhost");
        MAIL_PROPERTIES.setProperty("mail.imap.proxy.port", "18081");
```

In that example, we use IMAP to fetch emails, and this is what happens:

```
[2022-12-07 08:43:45.147] [INFO] Open: Socket[addr=/127.0.0.1,port=34576,localport=18081] 
[2022-12-07 08:43:45.148] [INFO] Socket[addr=/127.0.0.1,port=34576,localport=18081] read 85 bytes 
[2022-12-07 08:43:45.149] [INFO] CONNECT 0.0.0.0:18004 HTTP/1.1
Host: 0.0.0.0:18004
Proxy-Connection: keep-alive

 
[2022-12-07 08:43:45.149] [INFO] Open: Socket[addr=jbescos-PORTEGE-X40-K/127.0.1.1,port=18004,localport=56492] 
[2022-12-07 08:43:45.150] [INFO] Socket[addr=jbescos-PORTEGE-X40-K/127.0.1.1,port=18004,localport=56492] read 60 bytes 
[2022-12-07 08:43:45.150] [INFO] * OK JAMES IMAP4rev1 Server  Server 1ece50b148c8 is ready.
 
[2022-12-07 08:43:45.151] [INFO] Socket[addr=/127.0.0.1,port=34576,localport=18081] read 15 bytes 
[2022-12-07 08:43:45.151] [INFO] B0 CAPABILITY
 
[2022-12-07 08:43:45.153] [INFO] Socket[addr=jbescos-PORTEGE-X40-K/127.0.1.1,port=18004,localport=56492] read 200 bytes 
[2022-12-07 08:43:45.153] [INFO] * CAPABILITY NAMESPACE QUOTA IMAP4rev1 QRESYNC UNSELECT WITHIN SASL-IR ENABLE SEARCHRES UIDPLUS CHILDREN AUTH=PLAIN LITERAL+ ANNOTATION ESEARCH IDLE I18NLEVEL=1 STARTTLS
B0 OK CAPABILITY completed.
 
[2022-12-07 08:43:45.154] [INFO] Socket[addr=/127.0.0.1,port=34576,localport=18081] read 23 bytes 
[2022-12-07 08:43:45.154] [INFO] B1 AUTHENTICATE PLAIN
 
[2022-12-07 08:43:45.155] [INFO] Socket[addr=jbescos-PORTEGE-X40-K/127.0.1.1,port=18004,localport=56492] read 4 bytes 
[2022-12-07 08:43:45.155] [INFO] + 
 
[2022-12-07 08:43:45.155] [INFO] Socket[addr=/127.0.0.1,port=34576,localport=18081] read 34 bytes 
[2022-12-07 08:43:45.155] [INFO] AHVzZXIwMkBqYW1lcy5sb2NhbAAxMjM0
 
[2022-12-07 08:43:45.158] [INFO] Socket[addr=jbescos-PORTEGE-X40-K/127.0.1.1,port=18004,localport=56492] read 31 bytes 
[2022-12-07 08:43:45.158] [INFO] B1 OK AUTHENTICATE completed.
 
[2022-12-07 08:43:45.158] [INFO] Socket[addr=/127.0.0.1,port=34576,localport=18081] read 15 bytes 
[2022-12-07 08:43:45.158] [INFO] B2 CAPABILITY
 
[2022-12-07 08:43:45.159] [INFO] Socket[addr=jbescos-PORTEGE-X40-K/127.0.1.1,port=18004,localport=56492] read 200 bytes 
[2022-12-07 08:43:45.159] [INFO] * CAPABILITY NAMESPACE QUOTA IMAP4rev1 QRESYNC UNSELECT WITHIN SASL-IR ENABLE SEARCHRES UIDPLUS CHILDREN AUTH=PLAIN LITERAL+ ANNOTATION ESEARCH IDLE I18NLEVEL=1 STARTTLS
B2 OK CAPABILITY completed.
 
[2022-12-07 08:43:45.160] [INFO] Socket[addr=/127.0.0.1,port=34576,localport=18081] read 17 bytes 
[2022-12-07 08:43:45.160] [INFO] B3 SELECT INBOX
 
[2022-12-07 08:43:45.180] [INFO] Socket[addr=jbescos-PORTEGE-X40-K/127.0.1.1,port=18004,localport=56492] read 353 bytes 
[2022-12-07 08:43:45.181] [INFO] * FLAGS (\Answered \Deleted \Draft \Flagged \Seen)
* 1 EXISTS
* 1 RECENT
* OK [UIDVALIDITY 127588542] UIDs valid
* OK [UNSEEN 1] MailboxMessage 1 is first unseen
* OK [PERMANENTFLAGS (\Answered \Deleted \Draft \Flagged \Seen \*)] Limited
* OK [HIGHESTMODSEQ 35] Highest
* OK [UIDNEXT 12] Predicted next UID
B3 OK [READ-WRITE] SELECT completed.
 
[2022-12-07 08:43:45.189] [INFO] Socket[addr=/127.0.0.1,port=34576,localport=18081] read 48 bytes 
[2022-12-07 08:43:45.190] [INFO] B4 FETCH 1 (ENVELOPE INTERNALDATE RFC822.SIZE)
 
[2022-12-07 08:43:45.195] [INFO] Socket[addr=jbescos-PORTEGE-X40-K/127.0.1.1,port=18004,localport=56492] read 365 bytes 
[2022-12-07 08:43:45.195] [INFO] * 1 FETCH (INTERNALDATE "07-Dec-2022 07:43:44 +0000" RFC822.SIZE 1026 ENVELOPE ("Wed, 7 Dec 2022 08:43:44 +0100 (CET)" "Hello Demo!" ((NIL NIL "user01" "james.local")) ((NIL NIL "user01" "james.local")) ((NIL NIL "user01" "james.local")) ((NIL NIL "user02" "james.local")) NIL NIL NIL "<1783593083.1.1670399024094@jbescos-PORTEGE-X40-K>"))
B4 OK FETCH completed.
 
[2022-12-07 08:43:45.198] [INFO] Socket[addr=/127.0.0.1,port=34576,localport=18081] read 52 bytes 
[2022-12-07 08:43:45.198] [INFO] B5 FETCH 1 (BODY.PEEK[HEADER.FIELDS (Newsgroups)])
 
[2022-12-07 08:43:45.203] [INFO] Socket[addr=jbescos-PORTEGE-X40-K/127.0.1.1,port=18004,localport=56492] read 78 bytes 
[2022-12-07 08:43:45.203] [INFO] * 1 FETCH (BODY[HEADER.FIELDS (Newsgroups)] {2}

)
B5 OK FETCH completed.
 
[2022-12-07 08:43:45.205] [INFO] Socket[addr=/127.0.0.1,port=34576,localport=18081] read 28 bytes 
[2022-12-07 08:43:45.205] [INFO] B6 FETCH 1 (BODYSTRUCTURE)
 
[2022-12-07 08:43:45.210] [INFO] Socket[addr=jbescos-PORTEGE-X40-K/127.0.1.1,port=18004,localport=56492] read 377 bytes 
[2022-12-07 08:43:45.210] [INFO] * 1 FETCH (BODYSTRUCTURE (("TEXT" "PLAIN" ("charset" "us-ascii") NIL NIL "7BIT" 37 0 NIL NIL NIL NIL)("TEXT" "PLAIN" ("charset" "us-ascii" "name" "attachent2788585044665364406.txt") NIL NIL "7BIT" 0 0 NIL ("attachment" ("filename" "attachent2788585044665364406.txt")) NIL NIL) "MIXED" ("boundary" "----=_Part_0_1711574013.1670399024069") NIL NIL NIL))
B6 OK FETCH completed.
 
[2022-12-07 08:43:45.218] [INFO] Socket[addr=/127.0.0.1,port=34576,localport=18081] read 28 bytes 
[2022-12-07 08:43:45.218] [INFO] B7 FETCH 1 (BODY[1]<0.37>)
 
[2022-12-07 08:43:45.231] [INFO] Socket[addr=jbescos-PORTEGE-X40-K/127.0.1.1,port=18004,localport=56492] read 114 bytes 
[2022-12-07 08:43:45.231] [INFO] * 1 FETCH (FLAGS (\Recent \Seen) BODY[1]<0> {37}
Hello, this is a sample email message)
B7 OK FETCH completed.
 
[2022-12-07 08:43:45.232] [INFO] Socket[addr=/127.0.0.1,port=34576,localport=18081] read 10 bytes 
[2022-12-07 08:43:45.233] [INFO] B8 CLOSE
 
[2022-12-07 08:43:45.237] [INFO] Socket[addr=jbescos-PORTEGE-X40-K/127.0.1.1,port=18004,localport=56492] read 24 bytes 
[2022-12-07 08:43:45.237] [INFO] B8 OK CLOSE completed.
 
[2022-12-07 08:43:45.237] [INFO] Socket[addr=/127.0.0.1,port=34576,localport=18081] read 11 bytes 
[2022-12-07 08:43:45.238] [INFO] B9 LOGOUT
 
[2022-12-07 08:43:45.238] [INFO] Socket[addr=jbescos-PORTEGE-X40-K/127.0.1.1,port=18004,localport=56492] read 61 bytes 
[2022-12-07 08:43:45.238] [INFO] * BYE IMAP4rev1 Server logging out
B9 OK LOGOUT completed.
 
[2022-12-07 08:43:45.239] [INFO] Close: Socket[addr=jbescos-PORTEGE-X40-K/127.0.1.1,port=18004,localport=56492] 
[2022-12-07 08:43:45.239] [INFO] Close: Socket[addr=/127.0.0.1,port=34576,localport=18081]
```
It looks it is working fine and it does not hang.

Your IMAP server is closing the connections after 3 seconds. It is strange this only happens when non-TLS connection.

Just to discard this is not an issue in your IMAP server, you can try my [example](https://github.com/jbescos/jakartaEE10MailDemo) and configure the proxy in the same way I did (modify the host and port).

**Comment by nicowiggersiv** [comment]
Hi @jbescos ,

thanks for the quick feedback.

You are right, the connection looks fine in your case but it is also fine in most cases at our side, too. I think I need to add a few more information about what I have done and seen so far: We have an application that polls for new mails on a mailbox. The connection to the imap server via the proxy usually works fine, there are only rare cases where the connection fails with the bye/timeout message from the server. It is around 0,5 % of the cases where the connection fails. The debug output of javamail looked fine, it looked like the server did not send a greeting message and then the client waits until it receives the bye/timeout message. So I have run tcpdump to see if the server does not send the greeting message. The wireshark screenshot shows the dump of connection that failed. This dump was created on the client host. As you can see in packet 43508, the server did send the imap greeting message. So I have compared this tcp stream with the tcp streams of successful connections. It looked like the only difference is time. On successful connections the greeting message is received a little bit later, more than 1 ms, while in case of the connection fail it is < 1 ms. This made me check the javamail source code and the usage of the BufferedReader explains this behavior. It may read more data from the socket than probably expected by this implementation. When the greeting is received very soon, together with the HTTP 200, the BufferedReader will read as much as 8 kB (default buffer size in BufferedReader) from the socket. The loop will break wenn the \CR\LF\CR\LF marks the end of the HTTP response. However, as the BufferedReader is discarded after proxyConnect(), a greeting message that may alreay have been received in the BufferedReader will be lost. So the client waits for the greeting and the server waits for the greeting response. The server then ends the session after a timeout.

The BufferedReader bug also explains why this issue only happens on non-TLS connections: In case of TLS the server does not send the greeting message right after the tcp connection is established. So the BufferedReader does not read to much data from the socket, proxyConnect() returns, the client proceeds with the TLS handshake and **after that** the server sends its greeting message.

You might be able to see this issue if you try to connect to the imap service multiple times. Maybe this also depends on some OS/network configurations. Not sure about that. Please have a look at the proxyConnect() implementation. I guess you will come to the same conclusion when looking at the source code.

**Comment by jbescos** [comment]
I get your point.

Actually this will never happen in my HTTP proxy because the first CONNECT returns 200 without opening a connection to the destination. Unfortunately, IMAP responds with a greeting message just establishing a connection (you don't need to send anything), then it is possible that you receive the 200 and the OK during the loop.

I think this fix requires 2 fixes:
1. Do not use BufferedReader. Actually we only need to read the first line, so there is no need for performance reasons. In this way we avoid the possibility that the server greeting is sent and cached in the buffer.
2. Read only the first line. My understanding is that there will be no ACK till the moment the bytes containing the server greeting are read.

I will attach here a jar with the fix, in case you have non production environments to verify the fix work. I will also do my own tests.

**Comment by nicowiggersiv** [comment]
@jbescos The HTTP response from the proxy may consist of more than one line. Hence it would be necessary for proxyConnect() to read all HTTP response lines until [0x0a, 0x0a], while reading at least the HTTP response code.

I have a test environment available and will be happy to test any changes.

**Comment by jbescos** [comment]
Right, it should be till it finds \r\n\r\n. I guess that is what you mean with [0x0a, 0x0a]

**Comment by jbescos** [comment]
[test.zip](https://github.com/eclipse-ee4j/angus-mail/files/10176615/test.zip)

**Comment by nicowiggersiv** [comment]
> Right, it should be till it finds \r\n\r\n. I guess that is what you mean with [0x0a, 0x0a]
Yes, you are right. It should be \r\n\r\n.

Thanks @jbescos . I have created a new build with the fixed jar and have deployed it in the test environment. I will see if this issue occurs again and will get back here tomorrow with the result of this run.

**Comment by nicowiggersiv** [comment]
@jbescos I don't see any more issues in my test environment using your test build (test.zip). Looks good to me. Source change as well. Would be happy to see this change in master and the next release.
