### ISSUE TITLE
MimeMessage.getContent results in ArrayStoreException

### ISSUE THREAD

**Issue by MartinHenke71** [eclipse-ee4j/angus-mail#67]
When accessing getContent on a MimeMessage on an IMAP account, I get this error:
```
java.lang.ArrayStoreException: null
	at java.lang.System.arraycopy(Native Method) ~[?:1.8.0_322]
	at java.util.ArrayList.toArray(ArrayList.java:414) ~[?:1.8.0_322]
	at jakarta.activation.MailcapCommandMap.<init>(MailcapCommandMap.java:181) ~[jakarta.activation-api-2.1.1.jar:?]
	at jakarta.activation.CommandMap.getDefaultCommandMap(CommandMap.java:60) ~[jakarta.activation-api-2.1.1.jar:?]
	at jakarta.activation.DataHandler.getCommandMap(DataHandler.java:128) ~[jakarta.activation-api-2.1.1.jar:?]
	at jakarta.activation.DataHandler.getDataContentHandler(DataHandler.java:587) ~[jakarta.activation-api-2.1.1.jar:?]
	at jakarta.activation.DataHandler.getContent(DataHandler.java:515) ~[jakarta.activation-api-2.1.1.jar:?]
	at jakarta.mail.internet.MimeMessage.getContent(MimeMessage.java:1498) ~[jakarta.mail-1.1.0.jar:?]
```
I am using hMailServer version 5.6.8-B2574.
The project is using Java 8 64bit (Eclipse Adoptium jdk-8.0.322.6-hotspot).

Issue #624 mentioned a similar issue in a comment with this stacktrace:

```
Can't send email: java.lang.ArrayStoreException: arraycopy: element type mismatch: can not cast one of the elements of java.lang.Object[] to the type of the destination array, jakarta.activation.MailcapRegistry
	at java.base/java.lang.System.arraycopy(Native Method)
	at java.base/java.util.ArrayList.toArray(ArrayList.java:401)
	at jakarta.activation.MailcapCommandMap.<init>(MailcapCommandMap.java:181)
	at jakarta.activation.CommandMap.getDefaultCommandMap(CommandMap.java:60)
	at jakarta.activation.DataHandler.getCommandMap(DataHandler.java:128)
	at jakarta.activation.DataHandler.getDataContentHandler(DataHandler.java:587)
	at jakarta.activation.DataHandler.getContent(DataHandler.java:515)
	at jakarta.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1505)
	at jakarta.mail.internet.MimeMessage.updateHeaders(MimeMessage.java:2246)
	at jakarta.mail.internet.MimeMessage.saveChanges(MimeMessage.java:2206)
	at jakarta.mail.Transport.send(Transport.java:99)
```

For me, the workaround to downgrade jakarta.acivation-api to 2.0.1 also worked.

**Comment by jbescos** [comment]
Just remove any dependency related to activation and mail and add this one:
```
<dependency>
    <groupId>org.eclipse.angus</groupId>
    <artifactId>angus-mail</artifactId>
    <version>1.1.0</version>
</dependency>
```

That brings the mail-api, activation-api, angus-mail and angus-activation.

**Comment by MartinHenke71** [comment]
I am using angus-mail 1.1.0 already.
This is from my POM file with the workaround:
```
<dependency>
    <!-- Fixes java.lang.ArrayStoreException: null with org.eclipse.angus -->
    <groupId>jakarta.activation</groupId>
    <artifactId>jakarta.activation-api</artifactId>
    <version>2.0.1</version>
</dependency>
<dependency>
    <groupId>org.eclipse.angus</groupId>
    <artifactId>jakarta.mail</artifactId>
    <version>1.1.0</version>
    <exclusions>
        <exclusion>
            <!-- Fixes java.lang.ArrayStoreException: null with jakarta.activation -->
            <groupId>jakarta.activation</groupId>
            <artifactId>jakarta.activation-api</artifactId>                        
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by MartinHenke71** [comment]
This results in the same error as it also references jakarta-activation 2.1.1. Downgrading to jakarta-activation 2.0.1 solves it.

```
<dependency>
    <groupId>jakarta.activation</groupId>
    <artifactId>jakarta.activation-api</artifactId>
    <version>2.0.1}</version>
</dependency>
<dependency>
    <groupId>org.eclipse.angus</groupId>
    <artifactId>angus-mail</artifactId>
    <version>1.1.0</version>
    <exclusions>
        <exclusion>
            <groupId>jakarta.activation</groupId>
            <artifactId>jakarta.activation-api</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by lukasj** [comment]
same as #37
